[mypy]
plugins = pydantic.mypy
strict = True
warn_return_any = False
show_error_context = True
pretty = True
follow_imports = silent
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True
no_implicit_reexport = True
disallow_untyped_defs = True

[pydantic-mypy]
init_forbid_extra = True
warn_required_dynamic_aliases = True

[mypy-docs.source.*]
ignore_errors = True
